---
title: "Balance Communication Project"
author: "Levi_Bagwell"
date: "April 16, 2020"
output: html_document

Goals: Create a code using python that will communicate with a balance, take readings at certain time intervals, and also put those readings into a .csv file.

Part 1: Levi - Establish communication with balance. 

#!/usr/bin/env python3
import time
import serial
import csv

def conscale():
	ser=serial.Serial(
		port='/dev/ttyUSB0',
		baudrate=9600,
		parity='N',
		stopbits=serial.STOPBITS_ONE,
		bytesize=seril.SEVENBITS,
		timeout=None);
	x=ser.readline()
	return x
	
Resources Consulted: 
- Balance Communication (instructables.com)
- Software Interfaces Sartorius Balances to PC(windmill.co.uk)
- Balance Communication Software WinCT (Balances.com)

Notes: I was not succesful at getting the code to interface with the balance. I was able to find the serial port and get an error code back that said "device reports readiness to read but returned no data". I believe I was extremly close to getting this code to work with some more troublshooting with the code and the settings on the balance but unfortunatly ran out of time. 

Part 2: Gus - Design code to take readings at certain time intervals
#For the function i am contributing to, i am looking into possible software that will allow the scale to take readings at certain time intervals. I have been specifically looking into RsWeight programs to help with the issue. In the program, one can set many perameters and take readings at specific intervals. There is options in this program to export to an Excell file and have the data arranged respectively. Need to see what components are required for the specific program and if its a possibility.
I believe the code below will take readings every 10 seconds by continuously exucuting Levis code.
I need to figure out a stop code so it will not take measurments continuously


import time

def readmass():
    LEVIS CODE IS INSERTED HERE I BELIEVE
    time.sleep(10)

while True:
    readmass()
    
Some redactions... this is edited code that has a "stop time" 
Emily needs to add csv file code

def readmass():
	t_end = time.time() + 15;
	emily needs to make csv file to report to
		while time.time() < t_end:
			'python writes to csv'
			time.sleep(3)
		
    
Resources Consulted:
- Software info (https://www.aandd.jp/products/software/winct.html)
- Python guide https://docs.python.org/3.4/library/time.html

Part 3: Emily - Design code to insert readings into certain parts of a .csv file.
After the readings are collected at specific time intervals and recorded, they will need to be placed in an orderly fasion in a program. 
Excel will not be used, but rather a csv file. A csv file is is a delimited text file that uses a comma to separate values. 
A CSV file is different than a XLS file because a CSV format is a plain text format in which values are seperated by commas. An XLS file format is an Excel sheets binary file format that hold information about all the worksheets in a file, both content and formatting. 
Code will be created in order to place the recordings in certain cells in the .csv file. The recordings will be labeled accordingly using a code. 
This is the last step in the project, so research is continuing on the best way to format the data in the .csv file, while we establish communication with the scale. 
This is just a start there may need to be more added.

Import CSV
Result = ()
with open('output.csv', 'w') as csvfile:
    csvwriter = csv.writer(csvfile)
    for row in result.items():
        csvwriter.writerow(row)
        
Resources Consulted:
CSV file management: https://www.geeksforgeeks.org/csv-file-management-using-c/
What is a CSV File and How to open the CSV File Format: https://www.freecodecamp.org/news/what-is-a-csv-file-and-how-to-open-the-csv-file-format/


THE CODE AS OF 05/4/20 @11:30 AM

import time
import serial
import csv

def conscale():
	ser=serial.Serial(
		port='/dev/ttyUSB0',
		baudrate = 9600,
		parity=serial.PARITY_EVEN,
		stopbits=serial.STOPBITS_ONE,
		bytesize=serial.SEVENBITS,
		timeout=None);
		
	x=ser.readline()
	return x
	

def readmass():
	t_end = time.time() + 15;
	with open('mass.csv', 'w', newline='') as f:
		csvwriter = csv.writer(f, delimiter = ',',quotechar='|', quoting=csv.QUOTE_MINIMAL )
		while time.time() < t_end:
			csvwriter.writerow([conscale()])
			time.sleep(3)
			
	
 readmass()
